# Search and replace the values below with the correct values for your app
app_name: Zamry Wallet
launcher_name: Zamry Wallet
package_name: zamry_wallet
description: "Zamry's non-custodial wallet for fiat and crypto"
bundle_id_android: com.zamry.wallet
bundle_id_ios: com.zamry.wallet
firebase_project_id_prod: zamry-wallet
firebase_project_id_staging: zamry-app
flutter_version: 3.32.0

